### ISSUE TITLE
TLE to entity in cesium app

### ISSUE THREAD

**Issue by ryanpdx** [uniclogs/cesium#2]
Could get rid of the python flask app if the cesium app could handle converting the TLE to an Cesium entity.

This could be useful: https://community.cesium.com/t/27-5000-how-do-i-load-all-the-satellite-debris-data-tle-into-cesium/17355

**Comment by dmitri-mcguckin** [comment]
Turning it into a proper NextJS app, in order to take advantage of better module management.

**Comment by ryanpdx** [comment]
Cool, since that is leaning into React, I assume you have seen resium: https://github.com/reearth/resium

**Comment by ryanpdx** [comment]
I accidentally deleted my previous comment.

Cool, there is resium (react cesium): https://github.com/reearth/resium

**Comment by ryanpdx** [comment]
No longer needed. We actually want to keep the back for features like #6
