### ISSUE TITLE
Automatically fetch a fallback TLE if official TLE isn't avaliable

### ISSUE THREAD

**Issue by ThirteenFish** [uniclogs/cesium#5]
To my understanding we've been automatically updating the OreSat0 TLE but we can't auto-update the OreSat0.5 TLE because it hasn't been giving an official name yet. We've been updating manually using the provisional designator but can we do this automatically? As in provide the official name (ORESAT0.5) and an optional fallback (98867 possibly?) and if the official name fails pull from the fallback.

It's taken a while for us to get the official designator for OreSat0.5 and updating by hand is an easy task to get dropped.

**Comment by ryanpdx** [comment]
Completed in e55657
